### ISSUE TITLE
Find solution for saving huge Strings while trace-generation

### ISSUE THREAD

**Issue by mawHBT** [jenkinsci/peass-ci-plugin#121]
### What feature do you want to see added?

`de.dagere.peass.dependency.traces.OneTraceGenerator.generateTraceFiles` generates Strings which are to long to save:

```
java.lang.NegativeArraySizeException: -1283060862
	at java.base/java.lang.StringCoding.encodeUTF8(StringCoding.java:904)
	at java.base/java.lang.StringCoding.encode(StringCoding.java:502)
	at java.base/java.lang.String.getBytes(String.java:981)
	at de.dagere.peass.dependency.traces.TraceWriter.writeTraces(TraceWriter.java:54)
	at de.dagere.peass.dependency.traces.TraceWriter.writeTrace(TraceWriter.java:38)
	at de.dagere.peass.dependency.traces.OneTraceGenerator.writeTrace(OneTraceGenerator.java:111)
	at de.dagere.peass.dependency.traces.OneTraceGenerator.generateTraceFiles(OneTraceGenerator.java:104)
	at de.dagere.peass.dependency.traces.OneTraceGenerator.generateTrace(OneTraceGenerator.java:59)
```
A fix is needed.

**Comment by DaGeRe** [comment]
This should work since https://github.com/DaGeRe/peass/commit/f2fcdfb8609efb5f193432f029d438f7cd7c5fae, does this work for you?

**Comment by mawHBT** [comment]
Is working now.
