### ISSUE TITLE
Exception when used with Gitea Organization Plugin

### ISSUE THREAD

**Issue by Schattensilber** [jenkinsci/peass-ci-plugin#56]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.303.3
OS: Linux - 5.4.0-74-generic
---
ace-editor:1.1
ant:1.11
antisamy-markup-formatter:2.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
bootstrap4-api:4.6.0-3
bouncycastle-api:2.20
branch-api:2.6.3
build-timeout:1.20
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.0
cloudbees-folder:6.15
command-launcher:1.5
config-file-provider:3.8.0
configuration-as-code:1.54
credentials:2.6.1
credentials-binding:1.27
display-url-api:2.3.4
durable-task:1.35
echarts-api:5.1.0-2
email-ext:2.82
font-awesome-api:5.15.2-2
git:4.10.0
git-client:3.10.0
git-server:1.9
gitea:1.2.1
github:1.33.1
github-api:1.123
github-branch-source:2.10.2
gradle:1.36
h2-api:1.4.199
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
jackson2-api:2.12.3
jdk-tool:1.5
jjwt-api:0.11.2-9.c8b45b8bb173
jquery3-api:3.6.0-1
jsch:0.1.55.2
junit:1.49
ldap:2.6
lockable-resources:2.10
mailer:1.34
matrix-auth:2.6.6
matrix-project:1.19
momentjs:1.1.1
okhttp-api:3.14.9
pam-auth:1.6
peass-ci:0.1-SNAPSHOT (private-e8f69616-root)
pipeline-build-step:2.13
pipeline-github-lib:1.0
pipeline-graph-analysis:1.10
pipeline-input-step:2.12
pipeline-maven:3.10.0
pipeline-milestone-step:1.3.2
pipeline-model-api:1.8.4
pipeline-model-definition:1.8.4
pipeline-model-extensions:1.8.4
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.8.4
pipeline-stage-view:2.19
plain-credentials:1.7
plugin-util-api:2.1.0
popper-api:1.16.1-2
resource-disposer:0.15
scm-api:2.6.5
script-security:1.78
snakeyaml-api:1.29.1
ssh-credentials:1.19
ssh-slaves:1.31.5
sshd:3.0.3
strict-crumb-issuer:2.1.0
structs:1.23
timestamper:1.12
token-macro:2.15
trilead-api:1.0.13
workflow-aggregator:2.6
workflow-api:2.42
workflow-basic-steps:2.23
workflow-cps:2.90
workflow-cps-global-lib:2.18
workflow-durable-task-step:2.38
workflow-job:2.40
workflow-multibranch:2.23
workflow-scm-step:2.13
workflow-step-api:2.24
workflow-support:3.8
ws-cleanup:0.39

```

### Reproduction steps

- Jenkins with Gitea Organization multi branch job
- Context for below Exception: 
 - job name is GeoMap-Gitea-PermanEnt-daily
 - project name is geomap-backend
 - branch is master

### Results

Expected result:

Running properly

Actual result:

java.lang.RuntimeException: /var/jenkins_home/jobs/GeoMap-Gitea-PermanEnt-daily/jobs/geomap-backend/branches/master/peass-data neither contains workspace_peass nor GeoMap-Gitea-PermanEnt-daily » geomap-backend » master; one must exist for visualization!
	at de.dagere.peass.ci.helper.VisualizationFolderManager.getResultsFolders(VisualizationFolderManager.java:86)
	at de.dagere.peass.ci.logs.RTSLogFileReader.<init>(RTSLogFileReader.java:35)
	at de.dagere.peass.ci.logs.LogActionCreator.createRTSActions(LogActionCreator.java:30)
	at de.dagere.peass.ci.LocalPeassProcessManager.rts(LocalPeassProcessManager.java:72)
	at de.dagere.peass.ci.MeasureVersionBuilder.runAllSteps(MeasureVersionBuilder.java:148)
	at de.dagere.peass.ci.MeasureVersionBuilder.perform(MeasureVersionBuilder.java:120)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DaGeRe** [comment]
Thanks for the hint, this should work with [25a039b](https://github.com/DaGeRe/peass-ci/commit/25a039b4ed2dba69cf7f6ea48f1c0cf3184727aa), can you confirm this?

**Comment by Schattensilber** [comment]
can confirm.
